rule all:
    input:
        "final_report.txt"

rule align:
    output:
        "aligned.sam"
    shell:
        "echo 'STAR alignment completed' > aligned.sam"

rule bam_processing:
    input:
        "aligned.sam"
    output:
        "aligned_sorted.bam"
    shell:
        "echo 'BAM sorting completed' > aligned_sorted.bam"

rule featurecounts:
    input:
        "aligned_sorted.bam"
    output:
        "counts.txt"
    shell:
        "echo 'Gene counts generated' > counts.txt"

rule report:
    input:
        "counts.txt"
    output:
        "final_report.txt"
    shell:
        "echo 'RNA-seq workflow completed successfully' > final_report.txt"


